_wandb:
    value:
        cli_version: 0.20.0
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 3
                - 13
                - 55
                - 61
            "4": 3.12.3
            "5": 0.20.0
            "12": 0.20.0
            "13": linux-x86_64
batch_size:
    value: 16
grad_accumulation_steps:
    value: 32
input_bin:
    value: data/fineweb10B/fineweb_train_*.bin
input_val_bin:
    value: data/fineweb10B/fineweb_val_*.bin
learning_rate:
    value: 0.0018
log_wandb:
    value: true
model:
    value: d12
num_iterations:
    value: 4768
output_dir:
    value: pylog124M
save_every:
    value: 5000
sequence_length:
    value: 1024
val_batch_size:
    value: 16
val_loss_every:
    value: 128
warmdown_iters:
    value: 1024
warmup_iters:
    value: 256
weight_decay:
    value: 0.1
