wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/train_gpt2.py
    python_version: 3.12.9
    cli_version: 0.19.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1744309918
    t:
      1:
      - 1
      3:
      - 13
      - 42
      - 55
      4: 3.12.9
      5: 0.19.8
      13: linux-x86_64
